# Generated by Django 4.0.4 on 2022-05-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
                ('author', models.CharField(max_length=123)),
                ('price', models.CharField(max_length=123)),
                ('summery', models.TextField()),
                ('image', models.ImageField(upload_to='Book/')),
                ('create_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
